name: Deploy
on:
  pull_request:
    branches:
      - prod
    types: [closed]

jobs:
  sync:
    if: github.event.pull_request.merged == true
    name: Sync with main
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}
          fetch-depth: 0
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout prod
          git pull origin prod
          git rebase origin/main
          git push origin prod -f

  deploy:
    if: github.event.pull_request.merged == true
    name: Deploy production instance (via ssh)
    runs-on: ubuntu-latest
    needs: sync
    steps:
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd apps/ed-online-frontend/
            sh ./deploy.sh
